version: '1.0'
stages:
  - clone
  - test
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: clone
    type: git-clone
    repo: "henkerik/codefresh"
    revision: "${{CF_BRANCH}}"
    git: github
  frontend_unit_test:
    title: Frontend unit test
    stage: test
    image: node:13.10
    working_directory: ${{main_clone}}/app
    commands:
      - npm install
      - npm run build
    environment:
      - CI=true
#  backend_unit_test:
#    title: Backend unit test
#    stage: test
#    image: noamt/pre-cached-sbt
#    working_directory: ${{main_clone}}/api
#    commands:
#      - sbt test
  frontend_build:
    title: Building frontend
    type: build
    stage: build
    image_name: app
    tag: 'master'
    working_directory: ${{main_clone}}/app
    dockerfile: Dockerfile
#  backend_build:
#    title: Build backend
#    type: build
#    stage: build
#    image_name: api
#    tag: 'master'
#    working_directory: ${{main_clone}}/api
#    dockerfile: Dockerfile
